package bankomat.bankomatvvg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class izborIznosaIsplateDat implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public izborIznosaIsplateDat() {
    }

}