package bankomat.bankomatvvg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class izborIznosaBonaDat implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "izborIznosaBona")
   private java.lang.Integer izborIznosaBona;
   @org.kie.api.definition.type.Label(value = "iznosBona")
   private java.lang.String iznosBona;

   public izborIznosaBonaDat()
   {
   }

   public java.lang.Integer getIzborIznosaBona()
   {
      return this.izborIznosaBona;
   }

   public void setIzborIznosaBona(java.lang.Integer izborIznosaBona)
   {
      this.izborIznosaBona = izborIznosaBona;
   }

   public java.lang.String getIznosBona()
   {
      return this.iznosBona;
   }

   public void setIznosBona(java.lang.String iznosBona)
   {
      this.iznosBona = iznosBona;
   }

   public izborIznosaBonaDat(java.lang.Integer izborIznosaBona,
         java.lang.String iznosBona)
   {
      this.izborIznosaBona = izborIznosaBona;
      this.iznosBona = iznosBona;
   }

}