package bankomat.bankomatvvg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class izborIznosaIsplateDat implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "izborIznosaIsplateID")
   private java.lang.Integer izborIznosaIsplateID;
   @org.kie.api.definition.type.Label(value = "iznosIsplate")
   private java.lang.String iznosIsplate;

   public izborIznosaIsplateDat()
   {
   }

   public java.lang.Integer getIzborIznosaIsplateID()
   {
      return this.izborIznosaIsplateID;
   }

   public void setIzborIznosaIsplateID(java.lang.Integer izborIznosaIsplateID)
   {
      this.izborIznosaIsplateID = izborIznosaIsplateID;
   }

   public java.lang.String getIznosIsplate()
   {
      return this.iznosIsplate;
   }

   public void setIznosIsplate(java.lang.String iznosIsplate)
   {
      this.iznosIsplate = iznosIsplate;
   }

   public izborIznosaIsplateDat(java.lang.Integer izborIznosaIsplateID,
         java.lang.String iznosIsplate)
   {
      this.izborIznosaIsplateID = izborIznosaIsplateID;
      this.iznosIsplate = iznosIsplate;
   }

}