package bankomat.bankomatvvg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class listicIzborDat implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "listicIznorID")
   private java.lang.Integer listicIznorID;
   @org.kie.api.definition.type.Label(value = "izborListica")
   private java.lang.String izborListica;

   public listicIzborDat()
   {
   }

   public java.lang.Integer getListicIznorID()
   {
      return this.listicIznorID;
   }

   public void setListicIznorID(java.lang.Integer listicIznorID)
   {
      this.listicIznorID = listicIznorID;
   }

   public java.lang.String getIzborListica()
   {
      return this.izborListica;
   }

   public void setIzborListica(java.lang.String izborListica)
   {
      this.izborListica = izborListica;
   }

   public listicIzborDat(java.lang.Integer listicIznorID,
         java.lang.String izborListica)
   {
      this.listicIznorID = listicIznorID;
      this.izborListica = izborListica;
   }

}