package bankomat.bankomatvvg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class tipTransakcijeDat implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "tipTransakcijeID")
   private java.lang.Integer tipTransakcijeID;
   @org.kie.api.definition.type.Label(value = "izborTransakcije")
   private java.lang.String izborTransakcije;

   public tipTransakcijeDat()
   {
   }

   public java.lang.Integer getTipTransakcijeID()
   {
      return this.tipTransakcijeID;
   }

   public void setTipTransakcijeID(java.lang.Integer tipTransakcijeID)
   {
      this.tipTransakcijeID = tipTransakcijeID;
   }

   public java.lang.String getIzborTransakcije()
   {
      return this.izborTransakcije;
   }

   public void setIzborTransakcije(java.lang.String izborTransakcije)
   {
      this.izborTransakcije = izborTransakcije;
   }

   public tipTransakcijeDat(java.lang.Integer tipTransakcijeID,
         java.lang.String izborTransakcije)
   {
      this.tipTransakcijeID = tipTransakcijeID;
      this.izborTransakcije = izborTransakcije;
   }

}