package bankomat.bankomatvvg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class vrstaBonaDat implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Vrsta Bona")
   private java.lang.Integer vrstaBonaID;
   @org.kie.api.definition.type.Label(value = "tipBona")
   private java.lang.Integer tipBona;

   public vrstaBonaDat()
   {
   }

   public java.lang.Integer getVrstaBonaID()
   {
      return this.vrstaBonaID;
   }

   public void setVrstaBonaID(java.lang.Integer vrstaBonaID)
   {
      this.vrstaBonaID = vrstaBonaID;
   }

   public java.lang.Integer getTipBona()
   {
      return this.tipBona;
   }

   public void setTipBona(java.lang.Integer tipBona)
   {
      this.tipBona = tipBona;
   }

   public vrstaBonaDat(java.lang.Integer vrstaBonaID, java.lang.Integer tipBona)
   {
      this.vrstaBonaID = vrstaBonaID;
      this.tipBona = tipBona;
   }

}